### ISSUE TITLE
Coolify setup description improvement suggestion

### ISSUE THREAD

**Issue by amakhnev** [Mortalife/trigger-dev-coolify#1]
Hey, I used your docker-compose file and instructions and was able to run it; I just had a few hiccups, which I think would be great to have included in your documentation - to know how to marry it with coolify proxy magic. Feel free to update it or take it as information. 
1) There is no description of how to expose it to proxy / use custom DNS.  I managed to do it by setting up the web app domain as https://trigger.example.com:3030/ , which was not apparent as the port is not exposed in the docker-compose file. For information, I use Cloudflare DNS in proxied mode and explicitly made a "trigger" A record pointing to a public IP of the server.
2) SERVICE_FQDN_TRIGGER environmental variable - I had to set it up manually to https://trigger.example.com because it automatically resolved to some wrong address (probably internal) and broke some links (which are coming via APP_ORIGIN). I can see there is SERVICE_FQDN_TRIGGER_3030 environment variable - was it supposed to be SERVICE_FQDN_TRIGGER?

**Comment by Mortalife** [comment]
Hey, the `SERVICE_FQDN_TRIGGER_3030` is intentional. It tells the Coolify proxy to create a DNS entry (via the server wildcard steup with coolify) for the trigger service which points to the service at port 3030. You shouldn't need to do any specific configuration.

You can read more about it here: https://coolify.io/docs/knowledge-base/docker/compose/#coolifys-magic-environment-variables

Note specifically the example code.

**Comment by amakhnev** [comment]
Ok, thanks a lot, I got it. Some Coolify magic indeed :)  I guess it would be worth mentioning the Coolify setup is a server wildcard and if it's used for another scenario - it would be necessary to use other environmental variable values. Anyway, it works well, thanks a lot for sharing!

**Comment by Mortalife** [comment]
With a server wildcard is the default way of using Coolify AFAIK, I think it's okay to expect users who use a different method of connection like Cloudflare Tunnels or Tailscale to have enough understanding to make the system work given the context this repo provides. Either which way, glad things seem to be working for yourself.
